import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { createTheme, MantineProvider } from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';

import "../app/globals.css";



const theme = createTheme({
  colors: {
    // Custom white shades
    white: [
      '#ffffff',
      '#fafafa',
      '#f5f5f5',
      '#f0f0f0',
      '#e5e5e5',
      '#d4d4d4',
      '#a3a3a3',
      '#737373',
      '#525252',
      '#404040',
    ],
  },
  primaryColor: 'gray',
  defaultRadius: 'md',
  fontFamily: 'Inter, system-ui, sans-serif',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider theme={theme}>
          <Notifications zIndex={2000} />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
